stages:
  - builds

.multilib-deb: &multilib-deb |
  multilib=$(dpkg-architecture -q DEB_TARGET_MULTIARCH)

.multilib-rpm: &multilib-rpm |
  multilib=$(rpm --eval '%{_lib}')

.environment: &environment |
  export VIRT_PREFIX="$HOME/build/libvirt"
  export PATH="$VIRT_PREFIX/bin:$PATH"
  export C_INCLUDE_PATH="$VIRT_PREFIX/include"
  export LD_LIBRARY_PATH="$VIRT_PREFIX/$multilib"
  export PKG_CONFIG_PATH="$VIRT_PREFIX/$multilib/pkgconfig"
  export XDG_DATA_DIRS="$VIRT_PREFIX/share:/usr/share:/usr/local/share"
  export GI_TYPELIB_PATH="$VIRT_PREFIX/$multilib/girepository-1.0"
  export OSINFO_SYSTEM_DIR="$VIRT_PREFIX/share/osinfo"
  export MAKEFLAGS="-j $(getconf _NPROCESSORS_ONLN)"
  export CCACHE_BASEDIR="$(pwd)"
  export CCACHE_DIR="$CCACHE_BASEDIR/ccache"
  export CCACHE_MAXSIZE="50M"
  export PATH="$CCACHE_WRAPPERSDIR:$PATH"

.mingw-environment: &mingw-environment |
  export VIRT_PREFIX="$VIRT_PREFIX/$ABI/sys-root/mingw"
  export PKG_CONFIG_PATH="$VIRT_PREFIX/lib/pkgconfig"

.dco: &dco |
  pushd .
  ./scripts/require-dco.sh
  popd

.osinfo-db-tools-build: &osinfo-db-tools-build |
  pushd /tmp/
  git clone https://gitlab.com/libosinfo/osinfo-db-tools.git
  cd osinfo-db-tools
  mkdir build
  cd build
  meson .. . --prefix=$VIRT_PREFIX --werror
  $NINJA install
  popd

.osinfo-db-build: &osinfo-db-build |
  pushd /tmp/
  git clone https://gitlab.com/libosinfo/osinfo-db.git
  cd osinfo-db
  mkdir build
  cd build
  $MAKE -f ../Makefile VPATH=..
  $MAKE -f ../Makefile VPATH=.. check
  $MAKE -f ../Makefile VPATH=.. install OSINFO_DB_TARGET="--system"
  popd

.libosinfo-build: &libosinfo-build |
  pushd .
  mkdir build
  cd build
  meson .. . --prefix=$VIRT_PREFIX --werror
  $NINJA
  $NINJA install
  popd

.libosinfo-check: &libosinfo-check |
  pushd .
  cd build
  $NINJA test
  popd

.libosinfo-rpm: &libosinfo-rpm |
  if test "$RPM" = "skip"; then
    exit 0
  fi
  pushd .
  cd build
  sed -i -e 's/BuildRequires: *osinfo-db.*//' *.spec*
  $NINJA dist
  rpmbuild --clean --define "_topdir `pwd`/rpmbuild" -ta meson-dist/*.tar.xz
  popd

.libosinfo-mingw32-build: &libosinfo-mingw32-build |
  pushd .
  mkdir build_win32
  cd build_win32
  meson .. . --cross-file=/usr/share/mingw/toolchain-mingw32.meson --prefix=$VIRT_PREFIX -Denable-gtk-doc=false -Denable-tests=false -Denable-introspection=disabled -Denable-vala=disabled --werror
  $NINJA
  $NINJA install
  popd

.libosinfo-mingw64-build: &libosinfo-mingw64-build |
  pushd .
  mkdir build_win64
  cd build_win64
  meson .. . --cross-file=/usr/share/mingw/toolchain-mingw64.meson --prefix=$VIRT_PREFIX -Denable-gtk-doc=false -Denable-tests=false -Denable-introspection=disabled -Denable-vala=disabled --werror
  $NINJA
  $NINJA install
  popd

.x86_64-build-job-deb: &x86_64-build-job-deb
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib-deb
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-build
    - *libosinfo-build
    - *libosinfo-check

.x86_64-build-job-rpm: &x86_64-build-job-rpm
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib-rpm
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-build
    - *libosinfo-build
    - *libosinfo-check
    - *libosinfo-rpm

.mingw32-build-job: &mingw32-build-job
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME-cross-$CROSS:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib-rpm
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-build
    - *mingw-environment
    - *libosinfo-mingw32-build

.mingw64-build-job: &mingw64-build-job
  stage: builds
  image: quay.io/libvirt/buildenv-libosinfo-$NAME-cross-$CROSS:latest
  cache:
    paths:
      - ccache
    key: "$CI_JOB_NAME"
  script:
    - *multilib-rpm
    - *environment
    - *dco
    - *osinfo-db-tools-build
    - *osinfo-db-build
    - *mingw-environment
    - *libosinfo-mingw64-build

centos-7:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: centos-7
    RPM: skip

centos-8:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: centos-8

debian-9:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-9

debian-10:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-10

debian-sid:
  <<: *x86_64-build-job-deb
  variables:
    NAME: debian-sid

fedora-31:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-31

fedora-32:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-32

fedora-rawhide:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: fedora-rawhide

fedora-rawhide-cross-mingw32:
  <<: *mingw32-build-job
  variables:
    NAME: fedora-rawhide
    CROSS: mingw32

fedora-rawhide-cross-mingw64:
  <<: *mingw64-build-job
  variables:
    NAME: fedora-rawhide
    CROSS: mingw64

opensuse-151:
  <<: *x86_64-build-job-rpm
  variables:
    NAME: opensuse-151
    RPM: skip

ubuntu-1804:
  script:
  <<: *x86_64-build-job-deb
  variables:
    NAME: ubuntu-1804

ubuntu-2004:
  <<: *x86_64-build-job-deb
  variables:
    NAME: ubuntu-2004
